name: AuctionMaster
version: 1.0.0
main: cloud.coffeesystems.auctionmaster.AuctionMaster
description: The new Way to Auction Stuff - User to User, directly
author: Cancelcloud
website: https://github.com/cancel-cloud/AuctionMaster
api-version: "1.21"
dependencies:
  server:
    MCKotlin-Paper:
      required: true
      load: BEFORE

    Vault:
      required: true
      load: BEFORE
      join-classpath: true # so you can access Vault's classes

    XConomy:
      required: true
      load: BEFORE

permissions:
  auctionmaster.use:
    description: Allows the use of the auction system
    default: true
  auctionmaster.create:
    description: Allows creating auctions
    default: true
  auctionmaster.buy:
    description: Allows buying from auctions
    default: true
  auctionmaster.admin:
    description: Allows administrative access to the auction system
    default: op
  auctionmaster.notify:
    description: Receive notifications about database issues
    default: op
